### ISSUE TITLE
Idempotency

### ISSUE THREAD

**Issue by stmpy** [kylos101/python-with-prometheus#2]
https://github.com/kylos101/python-with-prometheus/blob/6fbf5a43712a686c183c6e4ab9c5549c608a59d7/scripts/cluster-install.sh#L17
https://github.com/kylos101/python-with-prometheus/blob/6fbf5a43712a686c183c6e4ab9c5549c608a59d7/scripts/cluster-install.sh#L18
https://github.com/kylos101/python-with-prometheus/blob/6fbf5a43712a686c183c6e4ab9c5549c608a59d7/scripts/cluster-install.sh#L22
https://github.com/kylos101/python-with-prometheus/blob/6fbf5a43712a686c183c6e4ab9c5549c608a59d7/scripts/cluster-install.sh#L23
https://github.com/kylos101/python-with-prometheus/blob/6fbf5a43712a686c183c6e4ab9c5549c608a59d7/scripts/cluster-install.sh#L24

should all consider idempotency - consecutive runs had issues with these lines

**Comment by kylos101** [comment]
Fixed in 689cb511bac2d98733830f75d2673c5a5e0677c6
